name: Magnusboe
favicon: null
layout_spectrum: 0.56101
typography_spectrum: 0.4032258
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Digital marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#d2c5d3'
    - '#a58c97'
    - '#0f0505'
    - '#a9231c'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
